# Generated by Django 3.2 on 2024-09-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Jobs',
        ),
    ]
