# Generated by Django 3.2 on 2024-10-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_booking_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pymentdetails',
        ),
    ]
