# Generated by Django 3.2 on 2024-11-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_pymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='baths_qty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='beds_qty',
            field=models.CharField(max_length=50),
        ),
    ]
