# Generated by Django 3.2 on 2024-11-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20241108_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingmodel',
            old_name='view_count',
            new_name='view_counttttt',
        ),
    ]
