# Generated by Django 3.2 on 2024-11-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_view_count_listingmodel_view_counttttt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingmodel',
            old_name='AC',
            new_name='citizenship_required',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='country',
            new_name='companys_country',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='address',
            new_name='companys_state',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='builtin_wardrobe',
            new_name='early_stage',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='apartment_type',
            new_name='experience_level',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='dish_washer',
            new_name='growth_stage',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='fencing',
            new_name='immediate_requirement',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='baths_qty',
            new_name='job_industry',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='beds_qty',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='title',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='floor_covering',
            new_name='late_stage',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='price',
            new_name='no_of_openings',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='internet',
            new_name='public_company',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='rooms',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='medical',
            new_name='sponsorship',
        ),
        migrations.RenameField(
            model_name='listingmodel',
            old_name='sqrft',
            new_name='view_count',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='view_counttttt',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='work_model',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
