# Generated by Django 3.2 on 2024-11-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20241108_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='experience_level',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='job_type',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='work_model',
            field=models.TextField(max_length=50),
        ),
    ]
