# Generated by Django 3.2 on 2024-11-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20241108_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='pymentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('user_id', models.CharField(default='', max_length=50)),
                ('owner_id', models.CharField(default='', max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=50)),
                ('prop_name', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
            ],
        ),
    ]
