# Generated by Django 3.2 on 2024-11-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_pymentdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pymentdetails',
            new_name='candidatedetails',
        ),
    ]
