# Generated by Django 3.2 on 2024-11-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_pymentdetails_candidatedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatedetails',
            old_name='Amount',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='candidatedetails',
            old_name='prop_name',
            new_name='salary',
        ),
    ]
