# Generated by Django 3.2 on 2024-11-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20241110_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='companys_country',
            field=models.CharField(max_length=50),
        ),
    ]
